### ISSUE TITLE
How edit frontpage

### ISSUE THREAD

**Issue by johnfelipe** [eduridden/moodle-theme_elegance#32] opened 2014-03-10 00:44 UTC
i need custom with:

![custom](https://f.cloud.github.com/assets/428820/2369845/16b0ba90-a7ed-11e3-9656-4a5378f1cde4.png)

**Comment by eduridden** [comment] 2014-03-10 00:46
Sorry John. This is for reporting bugs only. If you want custom jobs best to contact me directly or through the moodle forums. Closing this as not a bug

**Comment by johnfelipe** [comment] 2014-03-10 00:46
i send you mail, tnks

**Closed as completed by eduridden** 2014-03-10 00:46 UTC
